"""Initial migration

Revision ID: fcd42d3d42ba
Revises: 
Create Date: 2025-02-22 01:51:03.847713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd42d3d42ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo1', sa.String(length=100), nullable=False),
    sa.Column('equipo2', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('resultado1', sa.String(length=50), nullable=False),
    sa.Column('resultado2', sa.String(length=50), nullable=False),
    sa.Column('resultado3', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('modificaciones', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediccion')
    op.drop_table('partido')
    # ### end Alembic commands ###
